name: TimeAPI
version: 1.1
main: sh.okx.timeapi.PluginTimeAPI
author: Okx
commands:
  timeapi:
    permission: timeapi.command
    description: Display information about the API or parse a time.
    aliases: [tapi]

permissions:
    timeapi.*:
        children:
            timeapi.parse: true
            timeapi.command: true
    timeapi.parse:
        description: Parse TimeAPI strings
        default: op
    timeapi.command:
        description: TimeAPI Plugin Info
        default: true